//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OasisOneBack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificaciones_Servicios
    {
        public int Id_Calificacion { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public Nullable<int> Id_Servicio { get; set; }
        public Nullable<int> Puntuacion { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Servicios Servicios { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
