//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OasisOneBack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disponibilidad_Empleados
    {
        public int Id_Disponibilidad { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public string Dia_Semana { get; set; }
        public Nullable<System.TimeSpan> Hora_Inicio { get; set; }
        public Nullable<System.TimeSpan> Hora_Fin { get; set; }
        public Nullable<int> Id_Sede { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual Sedes Sedes { get; set; }
    }
}
