//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OasisOneBack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        public int Id_Factura { get; set; }
        public Nullable<int> Id_Usuario { get; set; }
        public Nullable<int> Id_Cita { get; set; }
        public Nullable<int> Id_Sede { get; set; }
        public Nullable<System.DateTime> Fecha_Emision { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Citas Citas { get; set; }
        public virtual Sedes Sedes { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
