//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OasisOneBack
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OasisOneEntities : DbContext
    {
        public OasisOneEntities()
            : base("name=OasisOneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calificaciones_Servicios> Calificaciones_Servicios { get; set; }
        public virtual DbSet<Categorias_Servicios> Categorias_Servicios { get; set; }
        public virtual DbSet<Citas> Citas { get; set; }
        public virtual DbSet<Disponibilidad_Empleados> Disponibilidad_Empleados { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Historial_Servicios> Historial_Servicios { get; set; }
        public virtual DbSet<Inventario_Productos> Inventario_Productos { get; set; }
        public virtual DbSet<Notificaciones> Notificaciones { get; set; }
        public virtual DbSet<Productos_Proveedor> Productos_Proveedor { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Sedes> Sedes { get; set; }
        public virtual DbSet<Servicios> Servicios { get; set; }
        public virtual DbSet<Sesiones_Empleados> Sesiones_Empleados { get; set; }
        public virtual DbSet<Sesiones_Usuarios> Sesiones_Usuarios { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
