//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OasisOneBack
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sesiones_Empleados
    {
        public int Id_Sesion { get; set; }
        public Nullable<int> Id_Empleado { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
        public string Token { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
